#!/bin/sh -e

# Clone .dotfiles to home directory
if [ "$(pwd)" == "$HOME/.dotfiles" ]; then
  # Need to useless push this dir so matches popd
  pushd $HOME/.dotfiles
else
  if [ -d "$HOME/.dotfiles" ]; then
    pushd $HOME/.dotfiles > /dev/null;
    echo $PWD
    echo git pull
    git pull
  else
    git clone git@github.com:jsonxr/.dotfiles.git $HOME/.dotfiles
    pushd $HOME/.dotfiles > /dev/null;
  fi
fi

echo
echo "Syncing HOME to $HOME"
echo
rsync -ahq HOME/ $HOME

export installed=`cat ~/.zshrc|grep "source ~/.dotfiles/source.sh"`
if [ "$installed" == "" ]; then
  echo "source ~/.dotfiles/source.sh" >> ~/.zshrc
fi

./install.sh

echo
echo "Run this command, or restart your terminal:"
echo
echo "    source ~/.zshrc"
echo
popd > /dev/null;
