#!/bin/sh -e

# Clone .dotfiles to home directory
if [ -d "$HOME/.dotfiles" ]; then
  pushd $HOME/.dotfiles > /dev/null;
  git pull
else
  echo cd ~
  echo git clone git@github.com:jsonxr/.dotfiles.git
  pushd $HOME/.dotfiles > /dev/null;
fi

echo
echo "Syncing HOME to $HOME"
echo
rsync -ahq HOME/ $HOME

export installed=`cat ~/.zshrc|grep "source ~/.dotfiles/source.sh"`
if [ "$installed" == "" ]; then
  echo "source ~/.dotfiles/source.sh" >> ~/.zshrc
fi

echo
echo "Run this command, or restart your terminal:"
echo
echo "    source ~/.zshrc"
echo
popd > /dev/null;